import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ResponsiveNavbar, ThemeProvider, ThemeToggle } from "@/components/ui";

import "../globals.css";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${font.className} antialiased bg-light-gray`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          {/* Navigation */}
          <ResponsiveNavbar />
          {/* Main Content */}

          {/* Main Content */}
          {children}

          {/* Footer */}

          {/* Theme Toggle */}
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
