import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import {
  ResponsiveNavbar,
  Footer,
  ThemeProvider,
  ThemeToggle,
} from "@/components/ui";

import "./globals.css";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${font.className} antialiased bg-light-gray`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <div className="min-h-screen flex flex-col">
            {/* Navigation */}
            <ResponsiveNavbar />

            {/* Main Content */}
            <main className="flex-1  pt-20 justify-center items-center">
              {children}
            </main>

            {/* Footer */}
            <Footer />

            {/* Theme Toggle */}
            <ThemeToggle />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
